source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

# from accounts.views import SignUp, UserDetailView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # path('create/', SignUp.as_view(), name='create'),
    # path('<int:pk>/', UserDetailView.as_view(), name='detail'),
]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),

]

source/webapp/urls.py
from django.urls import path

# from webapp.views import MinjustView, PeopleView
from webapp.views import SearchView, FirmaView, FirmaSecondView, IndexView, BudgetView, TenderView, SupplieredView

app_name = 'webapp'

urlpatterns = [
    # path('minjust/', MinjustView.as_view(), name='min_create'),
    # path('people/', PeopleView.as_view(), name='people_create'),
    path('', IndexView.as_view(), name='firma_main'),
    path('search/', SearchView.as_view(), name='search'),
    path('firma/<int:pk>/', FirmaView.as_view(), name='firma_detail'),
    path('firma/<int:pk>/budget/', BudgetView.as_view(), name='budget'),
    path('firma_2/<int:pk>/', FirmaSecondView.as_view(), name='firma_detail_2'),
    path("firma/<int:pk>/tenders/<str:firm_name>/", TenderView.as_view(), name="tender"),
    path("firma/<int:pk>/tenders_suppliered/<str:firm_name>/", SupplieredView.as_view(), name="tender_suppliered",),
]

source/webapp/views.py
import csv
from itertools import islice

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, render_to_response
from django.views import View
# import bulk_update_or_create
from django.views.generic import DetailView, ListView, TemplateView

from webapp.models import Firma, People, OpenBudget, Supliers, Tender, WinnerDetailed, Tizme, Farm, Bankrupt, \
    TenderBlackList, Gkpen, TenderBuyers, SupplierDetailed, Smi

PAGE_NUM_ITEMS = 10


class IndexView(ListView):
    model = Firma
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # firms = Firma.objects.count()
        # print(firms)
        context['firms_count'] = Firma.objects.count()
        context['peoples_count'] = People.objects.count()
        context['budgets_count'] = OpenBudget.objects.count()
        context['supliers_count'] = Supliers.objects.count()
        context['bankrupts_count'] = Bankrupt.objects.count()
        context['smi_count'] = Smi.objects.count()
        context['farm_count'] = Farm.objects.count()
        context['tender_buyers_count'] = TenderBuyers.objects.count()
        context['suppliers_count'] = Supliers.objects.count()
        context['gkpen_count'] = Gkpen.objects.count()
        context['supplier_det_count'] = SupplierDetailed.objects.count()
        context['tender_black_list_count'] = TenderBlackList.objects.count()
        context['tizme_count'] = Tizme.objects.count()
        context['winner_det_count'] = WinnerDetailed.objects.count()

        return context


# class SearchView(ListView):
#     model = Firma
#     template_name = 'search.html'

# def get_context_data(self, *, object_list=None, **kwargs):
#     context = super().get_context_data(object_list=object_list, **kwargs)
#     search_str_1 = self.request.GET.get('search_str')
#     if search_str_1:
#         search_str = " ".join(search_str_1.split())
#         if search_str:
#             firma_objects = Firma.objects.filter((Q(full_name_ru__icontains=search_str) | Q(full_name_kg__icontains=search_str)
#                                                   | Q(director__icontains=search_str) | Q(founders__icontains=search_str) |
#                                                   Q(inn__icontains=search_str))).order_by('full_name_kg')
#
#             # print(firma_objects)
#             paginator = Paginator(firma_objects, 5)
#             page = self.request.GET.get('page', 1)
#             # firma_objects = paginator.get_page(page)
#             context['firmas'] = paginator.get_page(page)
#             context['search_str'] = search_str
#
#         return context


class SearchView(ListView):
    template_name = "search.html"
    # paginate_by = 10
    context_object_name = "firmas"

    def get_queryset(self, *args, **kwargs):
        page = int(self.request.GET.get("page", 1))
        offset = (page - 1) * 10

        search_str_1 = self.request.GET.get("search_str")
        if search_str_1:
            search_str = " ".join(search_str_1.split())
            num_items = offset + PAGE_NUM_ITEMS
            if search_str:
                firma_objects = Firma.objects.filter(
                    (
                            Q(full_name_ru__icontains=search_str)
                            | Q(full_name_kg__icontains=search_str)
                            | Q(director__icontains=search_str)
                            | Q(founders__icontains=search_str)
                            | Q(inn__icontains=search_str)
                    )
                ).order_by("full_name_kg")[offset:num_items]
                return firma_objects

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        search_str = self.request.GET.get("search_str")
        person = search_str.upper().split()
        director_objects = []
        tizme_objects = []
        # print(person)
        page = int(self.request.GET.get("page_fiz", 1))
        offset = (page - 1) * PAGE_NUM_ITEMS
        page2 = int(self.request.GET.get("page_fiz_tizme", 1))
        offset2 = (page2 - 1) * PAGE_NUM_ITEMS
        num_items = offset + PAGE_NUM_ITEMS
        num_items2 = offset2 + PAGE_NUM_ITEMS
        if len(person) == 3:
            director_objects = People.objects.filter(
                (
                        Q(last_name__icontains=person[0])
                        & Q(first_name__icontains=person[1])
                        & Q(middle_name__icontains=person[2])
                )
            ).order_by("last_name", "first_name", "last_name")[offset:num_items]
            tizme_objects = Tizme.objects.filter(
                (
                        Q(last_name__icontains=person[0])
                        & Q(first_name__icontains=person[1])
                        & Q(middle_name__icontains=person[2])
                )
            ).order_by("last_name", "first_name", "last_name")[offset2:num_items2]
            # print(director_objects)
        if len(person) == 2:
            director_objects = People.objects.filter(
                (Q(last_name__icontains=person[0]) & Q(first_name__icontains=person[1]))
            ).order_by("last_name", "first_name", "last_name")[offset:num_items]
            tizme_objects = Tizme.objects.filter(
                (Q(last_name__icontains=person[0]) & Q(first_name__icontains=person[1]))
            ).order_by("last_name", "first_name", "last_name")[offset2:num_items2]
        if len(person) == 1:
            director_objects = People.objects.filter(
                (
                        Q(last_name__icontains=person[0])
                        | Q(first_name__icontains=person[0])
                        | Q(middle_name__icontains=person[0])
                )
            ).order_by("last_name", "first_name", "last_name")[offset:num_items]
            tizme_objects = Tizme.objects.filter(
                (
                        Q(last_name__icontains=person[0])
                        | Q(first_name__icontains=person[0])
                        | Q(middle_name__icontains=person[0])
                )
            ).order_by("last_name", "first_name", "last_name")[offset2:num_items2]
        context["tizmes"] = director_objects
        context["tizmes_2"] = tizme_objects
        context["search_str"] = self.request.GET.get("search_str")
        context["page_actual"] = int(self.request.GET.get("page", 1))
        context["page_actual_sti"] = int(self.request.GET.get("page_fiz", 1))
        context["page_actual_tizme"] = int(self.request.GET.get("page_fiz_tizme", 1))
        return context



# class FirmaView(ListView):
#     model = Firma
#     template_name = 'detail.html'
#     paginate_by = 5
#     paginate_orphans = 0
#
#     def get(self, request, *args, **kwargs):
#         firma_inn = []
#         context = {}
#         firma = Firma.objects.get(pk=kwargs['pk'])
#         firma_inn.append(firma)
#         director = firma.director.upper().split()
#         if len(director) == 3:
#             director_objects = People.objects.filter((Q(last_name__icontains=director[0]) & Q(first_name__icontains=director[1]) & Q(middle_name__icontains=director[2])))
#         else:
#             director_objects = People.objects.filter((Q(last_name__icontains=director[0]) & Q(
#                 first_name__icontains=director[1])))
#         firma_inn.append(director_objects)
#         # print(director_objects,'dfgfdg')
#         # for obj in director_objects:
#         #     print(obj.first_name)
#
#         inn = firma.inn
#         # print(inn)
#         supliers_objects = Supliers.objects.filter(Q(inn__icontains=inn))
#
#         context['supliers'] = supliers_objects
#         # context['budget'] = inn_object
#         context['firma'] = firma_inn
#         # print(context['firma'])
#
#         return render(request=request, template_name=self.template_name, context=context)


class FirmaView(TemplateView):
    template_name = "detail.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        firma = Firma.objects.get(pk=kwargs["pk"])
        founders = []
        if firma:
            founders_all = firma.founders
            founders_striped = founders_all.strip(" []")
            founders_splitted = founders_striped.split(",")
            for founder in founders_splitted:
                if "Замените на физическое лицо" not in founder:
                    founders.append(founder.strip(" ',"))

        inn = firma.inn
        supliers_objects = []
        buyers_objects = []
        director_objects = []
        gkpen_objects = []
        founders_director = []
        tizme_objects_all = []
        black_list_ojects = []
        bankrupts = []
        farms = []
        if inn:
            supliers_objects = Supliers.objects.filter(Q(inn__icontains=inn))
            buyers_objects = TenderBuyers.objects.filter(Q(inn__icontains=inn))
            gkpen_objects = Gkpen.objects.filter(Q(inn_okpo__icontains=inn))
            black_list_ojects = TenderBlackList.objects.filter(Q(inn__icontains=inn))
            bankrupts = Bankrupt.objects.filter(Q(tin__icontains=inn))
            farms = Farm.objects.filter(Q(inn__icontains=inn))
        director = firma.director
        founders_director.append(director)
        for founder in founders:
            founders_director.append(founder)

        for person in founders_director:
            person = person.upper().split()
            if len(person) == 3:
                nalog_objects = People.objects.filter(
                    (
                            Q(last_name__icontains=person[0])
                            & Q(first_name__icontains=person[1])
                            & Q(middle_name__icontains=person[2])

source/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Sled{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
    {% block styles %}{% endblock %}
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-white bg-white">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
{#            <div><a class="navbar-brand logo" href="{% url 'webapp:firma_main' %}">SLED</a></div>#}
            <div class="navbar-brand logo2"></div>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                    <ul class="navbar-nav ml-5">
                        {% block menu %}{% endblock %}
                    </ul>
                </ul>
{#                {% if request.user.is_authenticated %}#}
{#                    <span class="navbar-text"><a class="account" href="">{{ request.user }}</a></span>#}
{#                    <span><a class="nav-link cartin" href="{% url 'accounts:logout' %}">Выйти</a></span>#}
{#                {% else %}#}
{#                    <a href="{% url 'accounts:login' %}" class="nav-link btn menu-button"></a>#}
{#                {% endif %}#}
            </div>
        </div>
    </nav>
</header>
{#<div class="container">#}
    {% block content %}

    {% endblock %}
{#</div>#}
<footer>

</footer>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
<script type="application/javascript" src="{% static "js/main.js" %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/tender_suppliered.html
{% extends 'base.html' %}
{% block menu %}
    <a class="nav-link" href="{% url "webapp:firma_detail" firma.pk %}">{{ firma.full_name_ru }}</a>
{% endblock %}
{% block content %}
    <div class="header3 ">
        <div class="header3-cont container d-flex align-items-center justify-content-center flex-column position-relative">
            <a href="/">
                <div class="logo3">
                </div>
            </a>
            <nav class="base-navbar navbar-expand navbar-white">
                {#                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">#}
                {#                    <span class="navbar-toggler-icon"></span>#}
                {#                </button>#}
{#                <div class="collapse navbar-collapse" id="navbarTogglerDemo03">#}
{#                    <ul class="navbar-nav mr-auto mb-0 mb-md-2 mb-lg-0">#}
{#                        <ul class="navbar-nav ul-left">#}
{#                            <a class="nav-link active" aria-current="page" href="{% url 'webapp:firma_main' %}">Главная</a>#}
{#                            <a class="nav-link active" aria-current="page" href="{% url 'webapp:search' %}">Тарифы</a>#}
{#                            <a class="nav-link active" aria-current="page" href="{% url 'webapp:about' %}">О нас</a>#}
{#                        </ul>#}
{#                    </ul>#}
{#                    {% if request.user.is_authenticated %}#}
{#                        <span class="navbar-text"><a class="account" href="">{{ request.user }}</a></span>#}
{#                        <span><a class="nav-link cartin" href="{% url 'accounts:logout' %}">Выйти</a></span>#}
{#                    {% else %}#}
{#                        <a href="{% url 'accounts:login' %}" class="nav-link btn menu-button">Войти</a>#}
{#                        <a href="{% url 'accounts:login' %}" class="nav-link btn-success menu-button reg-btn">Регистрация</a>#}
{#                    {% endif %}#}
{#                </div>#}
            </nav>
        </div>

    </div>
    <div class="search-content">
        <div class="container-fluid">
            <dl class="row">
                <h3 class="text-center">Тендеры в котором фирма учавствовала</h3>
                <div class="table-responsive">
                    <table class="table table-responsive table-striped table-hover">
                        <thead>
                        <tr>
                            {#                <th scope="col">#</th>#}
                            <th scope="col">Номер тендера</th>
                            <th scope="col">Закупающая организация</th>
                            <th scope="col">Дата опубликования</th>
                            <th scope="col">Дата завершения</th>
                            <th scope="col">Название тендера</th>
                            <th scope="col">Общая сумма тендера</th>
                            <th scope="col">Номер лота</th>
                            <th scope="col">Название лота</th>
                            <th scope="col">Гокз</th>
                            <th scope="col">Форма гокз</th>
                            <th scope="col">Предложенная сумма</th>
                            <th scope="col">Планируемая сумма</th>
                            {#                <th scope="col"></th>#}
                        </tr>
                        </thead>
                        <tbody>
                        {% if tenders %}
                            {% for tender in tenders %}
                                <tr>
                                    {#                        <th scope="row"> {{ page_obj.number * 5 + forloop.counter0 }}</th>{{ value|add:"2" }}#}
                                    {% if tender.tender_num %}
                                        <td>{{ tender.tender_num }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.zak_org %}
                                        <td>{{ tender.zak_org }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.start %}
                                        <td>{{ tender.start }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.finish %}
                                        <td>{{ tender.finish }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.tender_name %}
                                        <td>{{ tender.tender_name }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.tender_summ %}
                                        <td>{{ tender.tender_summ }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.lots_number %}
                                        <td>{{ tender.lots_number }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.lots_name %}
                                        <td>{{ tender.lots_name }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.gokz %}
                                        <td>{{ tender.gokz }}</td>
                                    {% else %}
                                        <td>Без гокз</td>
                                    {% endif %}
                                    {% if tender.gokz_form %}
                                        <td>{{ tender.gokz_form }}</td>
                                    {% else %}
                                        <td>Без гокз</td>
                                    {% endif %}
                                    {% if tender.proposed_summ %}
                                        <td>{{ tender.proposed_summ }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.planned_summ %}
                                        <td>{{ tender.planned_summ }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {#                        <td class="more-btn"><b><a class="more" href="{% url "webapp:firma_detail" firma.pk %}">подробнее</a></b></td>#}
                                </tr>
                            {% endfor %}
                            {% if is_paginated %}
                                {#                        {% include 'partial/pagination.html' %}#}
                            {% endif %}

                        {% elif not tenders %}
                            <div class="main-block">
                                <span class="descr">Данных не обнаружено</span>
                            </div>
                        {% endif %}

                        </tbody>
                    </table>
                </div>

                {% if is_paginated %}
                    {% include 'partial/pagination.html' %}
                {% endif %}
            </dl>
        </div>
    </div>
{% endblock %}

source/webapp/templates/tender_winners.html
{% extends 'base.html' %}
{% block menu %}
    <a class="nav-link" href="{% url "webapp:firma_detail" firma.pk %}">{{ firma.full_name_ru }}</a>
{% endblock %}
{% block content %}
    <div class="header3 ">
        <div class="header3-cont container d-flex align-items-center justify-content-center flex-column position-relative">
            <a href="/">
                <div class="logo3">
                </div>
            </a>
            <nav class="base-navbar navbar-expand navbar-white">
                {#                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">#}
                {#                    <span class="navbar-toggler-icon"></span>#}
                {#                </button>#}
{#                <div class="collapse navbar-collapse" id="navbarTogglerDemo03">#}
{#                    <ul class="navbar-nav mr-auto mb-0 mb-md-2 mb-lg-0">#}
{#                        <ul class="navbar-nav ul-left">#}
{#                            <a class="nav-link active" aria-current="page" href="{% url 'webapp:firma_main' %}">Главная</a>#}
{#                            <a class="nav-link active" aria-current="page" href="{% url 'webapp:search' %}">Тарифы</a>#}
{#                            <a class="nav-link active" aria-current="page" href="{% url 'webapp:about' %}">О нас</a>#}
{#                        </ul>#}
{#                    </ul>#}
{#                    {% if request.user.is_authenticated %}#}
{#                        <span class="navbar-text"><a class="account" href="">{{ request.user }}</a></span>#}
{#                        <span><a class="nav-link cartin" href="{% url 'accounts:logout' %}">Выйти</a></span>#}
{#                    {% else %}#}
{#                        <a href="{% url 'accounts:login' %}" class="nav-link btn menu-button">Войти</a>#}
{#                        <a href="{% url 'accounts:login' %}" class="nav-link btn-success menu-button reg-btn">Регистрация</a>#}
{#                    {% endif %}#}
{#                </div>#}
            </nav>
        </div>

    </div>
    <div class="search-content">
        <div class="container-fluid">
            <dl class="row">
                <h3 class="text-center">Тендеры в котором фирма учавствовала</h3>
                <div class="table-responsive">
                    <table class="table table-responsive table-striped table-hover">
                        <thead>
                        <tr>
                            {#                <th scope="col">#</th>#}
                            <th scope="col">Номер тендера</th>
                            <th scope="col">Закупающая организация</th>
                            <th scope="col">Дата опубликования</th>
                            <th scope="col">Дата завершения</th>
                            <th scope="col">Название тендера</th>
                            <th scope="col">Общая сумма тендера</th>
                            <th scope="col">Номер лота</th>
                            <th scope="col">Название лота</th>
                            <th scope="col">Гокз</th>
                            <th scope="col">Форма гокз</th>
                            <th scope="col">Предложенная сумма</th>
                            <th scope="col">Планируемая сумма</th>
                            {#                <th scope="col"></th>#}
                        </tr>
                        </thead>
                        <tbody>
                        {% if tenders %}
                            {% for tender in tenders %}
                                <tr>
                                    {#                        <th scope="row"> {{ page_obj.number * 5 + forloop.counter0 }}</th>{{ value|add:"2" }}#}
                                    {% if tender.tender_num %}
                                        <td>{{ tender.tender_num }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.zak_org %}
                                        <td>{{ tender.zak_org }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.start %}
                                        <td>{{ tender.start }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.finish %}
                                        <td>{{ tender.finish }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.tender_name %}
                                        <td>{{ tender.tender_name }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.tender_summ %}
                                        <td>{{ tender.tender_summ }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.lots_number %}
                                        <td>{{ tender.lots_number }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.lots_name %}
                                        <td>{{ tender.lots_name }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.gokz %}
                                        <td>{{ tender.gokz }}</td>
                                    {% else %}
                                        <td>Без гокз</td>
                                    {% endif %}
                                    {% if tender.gokz_form %}
                                        <td>{{ tender.gokz_form }}</td>
                                    {% else %}
                                        <td>Без гокз</td>
                                    {% endif %}
                                    {% if tender.proposed_summ %}
                                        <td>{{ tender.proposed_summ }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {% if tender.planned_summ %}
                                        <td>{{ tender.planned_summ }}</td>
                                    {% else %}
                                        <td>Нет данных</td>
                                    {% endif %}
                                    {#                        <td class="more-btn"><b><a class="more" href="{% url "webapp:firma_detail" firma.pk %}">подробнее</a></b></td>#}
                                </tr>
                            {% endfor %}
                            {% if is_paginated %}
                                {#                        {% include 'partial/pagination.html' %}#}
                            {% endif %}

                        {% elif not tenders %}
                            <div class="main-block">
                                <span class="descr">Данных не обнаружено</span>
                            </div>
                        {% endif %}

                        </tbody>
                    </table>
                </div>

                {% if is_paginated %}
                    {% include 'partial/pagination.html' %}
                {% endif %}
            </dl>
        </div>
    </div>
{% endblock %}